# Generated by Django 6.0.3 on 2026-04-11 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='otp',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('resell', 'Resell'), ('new', 'New'), ('pdf', 'PDF'), ('free_book', 'Free Book')], default='resell', max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.book'),
        ),
        migrations.CreateModel(
            name='SyllabusBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('university_name', models.CharField(max_length=255)),
                ('semester', models.CharField(max_length=100)),
                ('subjects', models.JSONField(default=list)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='api.book')),
            ],
        ),
    ]
